import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/blockComponents/Footer";
import { Suspense } from "react";

// app/layout.tsx
import dynamic from 'next/dynamic';

const Navbar = dynamic(() => import('@/components/blockComponents/Navbar'));

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Loading component for navbar
function NavbarLoading() {
  return (
    <nav className="fixed top-0 left-0 right-0 z-40 bg-black/30 backdrop-blur-md border-b border-white/20">
      <div className="max-w-7xl mx-auto px-4 py-4">
        <div className="flex justify-between items-center">
          <div className="shrink-0">
            <h1 className="font-semibold text-green-400 text-4xl">Lavita</h1>
          </div>
        </div>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<NavbarLoading />}>
          <Navbar/>
        </Suspense>
        {children}
        <Footer/>
      </body>
    </html>
  );
}